
AllCops:
  Excludes:
    - 'app/assets/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'data/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'ssl/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'app/controller/users/**/*'
